import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const res = await fetch('https://fakestoreapi.com/products/category/jewelery')
  const storeData = await res.json()
  if (!storeData) {
    return {
      redirect: {
        destination: '/404',
        permanent: false,
      },
    }
  }

  return {
    // Pass data to the page via props
    // Incremental   Static  Regeneration
    revalidate: 1,
    props: { storeData: storeData }
  }
}

interface HomeProps {
  storeData: {
    "id": number,
    "title": string,
    "price": number,
    "description": string,
    "category": string,
    "image": string,
  }[]
}

const Home: NextPage<HomeProps> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="grid grid-cols-3 gap-2">
        {props.storeData.map((item, index) => {
          return (
            <div key={index}>
              <img width="50px" height="50px" alt={item.title} src={item.image} />
              <h1 className="text-3xl font-bold underline text-red-500">{item.category}</h1>
              {item.title}
              {item.description}
            </div>
          )
        })}
        </div>
      </main>
    </div>
  )
}

export default Home
